# Generated by Django 3.2.2 on 2021-06-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostquiz',
            old_name='quizdate',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='hostquiz',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
