# Generated by Django 3.2.2 on 2021-06-18 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210618_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostquiz',
            name='starttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
