# Generated by Django 3.2.2 on 2021-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hostquiz_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option_index',
            field=models.IntegerField(default=0),
        ),
    ]
