# Generated by Django 3.2.2 on 2021-07-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_questions_option_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='time_elapsed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
