# Generated by Django 3.2.2 on 2021-07-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answers_time_elapsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='time_elapsed',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
