# Generated by Django 3.2.2 on 2021-07-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_joinquiz_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinquiz',
            name='time_taken',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
