# Generated by Django 3.2.2 on 2021-07-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_joinquiz_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinquiz',
            name='score',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
